# Generated by Django 2.2.4 on 2019-08-10 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='identity_number',
            new_name='neighbour_number',
        ),
    ]
