# Generated by Django 2.2.4 on 2019-08-12 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0004_auto_20190811_1529'),
        ('users', '0003_remove_profile_neighbour_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='neighbourhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='neighbour.Neighbourhood'),
        ),
    ]
