# Generated by Django 2.2.4 on 2019-08-12 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190812_1729'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
