# Generated by Django 2.2.4 on 2019-08-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0002_auto_20190810_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='business_email',
        ),
        migrations.AlterField(
            model_name='business',
            name='business_email',
            field=models.CharField(max_length=30),
        ),
    ]
