# Generated by Django 2.2.4 on 2019-08-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0004_auto_20190811_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='name',
            field=models.CharField(default='kilimani', max_length=50),
        ),
    ]
