# Generated by Django 2.2.4 on 2019-08-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0005_auto_20190812_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='name',
            field=models.CharField(choices=[('Kilimani', 'KILIMANI'), ('jamuhuri', 'JAMUHURI'), ('kibera', 'KIBERA'), ('lavington', 'LAVINGTON'), ('kileleshwa', 'KILELESHWA'), ('kawangware', 'KAWANGWARE')], default='kilimani', max_length=50),
        ),
    ]
